### ISSUE TITLE
Issue with "fields" command

### ISSUE THREAD

**Issue by bertinatto** [scrapinghub/shubc#5] opened 2014-06-10 16:47 UTC
The following command return all items' fields, not just the "url":

`shubc items XXXX -fields="url"`

**Comment by andrix** [comment] 2014-06-15 23:31
@bertinatto I couldn't reproduce this issue, but you're using the options in the wrong other, it should be:

```
shubc -fields url items <job_id>
```

Can you check?

**Comment by bertinatto** [comment] 2014-06-16 00:34
@andrix 
Yes, the problem was the options' order.
Thanks.

**Comment by andrix** [comment] 2014-06-16 00:55
Thanks! Closing it.

**Closed as completed by andrix** 2014-06-16 00:55 UTC
